name: Python Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    environment:
      name: testing

    steps:
      # Get the files
      - uses: actions/checkout@v3

      # Python setup
      # TODO Check python version
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2

      - name: Install python dependencies
        run: |
          poetry install

      # Testing
      - name: Run Python tests with coverage
        run: |
          poetry run coverage run -m pytest -s tests

      # Coverage
      - name: Generate and upload coverage reports to Codecov
        run: |
          poetry run coverage xml
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
